### ISSUE TITLE
acceptSocket : Accept timed out

### ISSUE THREAD

**Issue by LW-G38** [willybernal/mlep#2]
Hi there,

I'm trying to run the example case on MATLAB 2019b and EnergyPlus v9.3. The OS is Mac OS Catalina and I have changed the JAVA version to 1.8.0_201. However, I keep getting the error message:

Error using mlepProcess/acceptSocket (line 106)
Java exception occurred:
java.net.SocketTimeoutException: Accept timed out
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)

Error in runsimple (line 44)
[status, msg] = ep.acceptSocket;

Can you please let me know if there is anything wrong during my set-up?

Many Thanks,

Wei

**Comment by mokandil** [comment]
@willybernal @LW-G38
Hi,
I have the same problem. I tested it on MATLAB 2019a, 2020a and EnergyPlus v9.3. Can you please explain how could you solve this problem?

`Error using mlepProcess/acceptSocket (line 107)
Java exception occurred:
java.net.SocketTimeoutException: Accept timed out

	at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)

	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)

	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)

	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)

	at java.net.ServerSocket.implAccept(ServerSocket.java:545)

	at java.net.ServerSocket.accept(ServerSocket.java:513)


Error in runsimple (line 44)
[status, msg] = ep.acceptSocket;`
